### ISSUE TITLE
Add engines to package.json

### ISSUE THREAD

**Issue by ivmartel** [ivmartel/dwv#1050]
The engines text specifies the compatible node versions (see [doc](https://nodejs.dev/learn/the-package-json-guide#engines)). This will produce an error if run in strict mode, otherwise a warning.

**Comment by ivmartel** [comment]
node v12 gives an encoding error:
> internal/encoding.js:398
    throw new ERR_ENCODING_NOT_SUPPORTED(encoding);
    ^
RangeError [ERR_ENCODING_NOT_SUPPORTED]: The "iso-8859-1" encoding is not supported
    at new TextDecoder (internal/encoding.js:398:15)
    at new A.dicom.DataReader (/home/yves/dev/src/github/local/node/parse/node_modules/dwv/dist/dwv.min.js:3:24376)
    at A.dicom.DicomParser.parse (/home/yves/dev/src/github/local/node/parse/node_modules/dwv/dist/dwv.min.js:3:45475)
