### ISSUE TITLE
Not a valid DICOM file (no magic DICM word found)

### ISSUE THREAD

**Issue by LeoReubelt** [ivmartel/dwv#1248]
I realize there have been a number of other issues entered for this error. But I have read them all and can't seem to figure it out.
DWV version - "dwv": "^0.30.8", 
I am loading my files as follows....

```
export const loadDicomFiles = (
    unzippedFiles: JSZipWithData[],
    divId: string,
    dataLoaded: () => void,
): any => {
    const app = new dwv.App();
    app.init({
        dataViewConfigs: { '*': [{ divId: divId }] },
    });

    app.addEventListener(`loadend`, (event: any) => {
        dataLoaded();
    });

    app.addEventListener(`error`, (event: any) => {
        console.error(`dicom error ----`, event);
    });

    const files = unzippedFiles.map((file) => {
        const blob = new Blob([file._data.compressedContent], {
            type: `application/dicom`,
        });

        return new File([blob], file.name);
    });

    app.loadFiles(files);
    return app;
};

```
- Some files work and other files don't. When they don't, i get 'Not a valid DICOM file (no magic DICM word found)'
- When I use https://github.com/ivmartel/dwv-react for the files that don't work using my functions, i get a different error.
```
          DwvComponent.js:282 TypeError: Cannot read properties of null (reading 'length')
             at A.image.ImageFactory.create (dwv.min.js:3:1)
             at h (dwv.min.js:3:1)
             at dwv.min.js:3:1
             at d.ondecodeditem [as onworkitem] (dwv.min.js:3:1)
             at Worker.o (dwv.min.js:3:1)
```

**Comment by LeoReubelt** [comment]
And using my code, with some files I get ....

```
Unhandled Runtime Error
Error: No JPEG Lossless decoder provided
```

**Comment by LeoReubelt** [comment]
And i checked the file. It does indeed have a 'DICM' prefix.

**Comment by ivmartel** [comment]
Could you share some faulty data?

**Comment by LeoReubelt** [comment]
thanks for getting back to me. i will ask if i can share the files. i don't think the data is faulty though. i checked and it does have the DICM prefix. and i can open it in other viewers.

**Comment by ivmartel** [comment]
Ah, yes, you are passing compressed data in the reconstructed files. The `app.loadFiles` method can take a zip file as input (as HTML [File](https://developer.mozilla.org/en-US/docs/Web/API/File)). There is also a `app.loadImageObject` method: see [application.js#L430](https://github.com/ivmartel/dwv/blob/v0.30.8/src/app/application.js#L430).

**Comment by LeoReubelt** [comment]
Yep you are right. If i give it uncompressed files, it works. Thanks for the help. 
It is odd though, using the same files, it works fine with compressed files if the files are not in a folder in the zip file.

**Comment by ivmartel** [comment]
Yes, the zip loader expects all files at the root of the zip. I did not put any logic to handle other file structures.

**Comment by LeoReubelt** [comment]
Thanks for the help.

**Comment by LeoReubelt** [comment]
On another note, thanks for doing this in general. I appreciate being able to work with this.

**Comment by ivmartel** [comment]
Glad it can help. I'd be happy to ear about your use case, either here or by email.
