### ISSUE TITLE
TypeError: e.set is not a function of Object.g.dicom.flattenArrayOfTypedArrays 

### ISSUE THREAD

**Issue by quinton-ashley** [ivmartel/dwv#370]
I get this error sometimes.  I tried to fix it myself but I can't figure out which function this object should be using.  In the non-minified version of dwv I believe the error occurs on line 4809.
```
TypeError: e.set is not a function
    at Object.g.dicom.flattenArrayOfTypedArrays (/Users/qashto/Dropbox/web/automaDICOM/node_modules/dwv/dist/dwv.min.js:4:12582)
    at g.dicom.DataWriter.writePixelDataElementValue (/Users/qashto/Dropbox/web/automaDICOM/node_modules/dwv/dist/dwv.min.js:4:10929)
    at g.dicom.DataWriter.writeDataElement (/Users/qashto/Dropbox/web/automaDICOM/node_modules/dwv/dist/dwv.min.js:4:11851)
    at g.dicom.DataWriter.writeDataElementItems (/Users/qashto/Dropbox/web/automaDICOM/node_modules/dwv/dist/dwv.min.js:4:9882)
    at g.dicom.DataWriter.writeDataElementValue (/Users/qashto/Dropbox/web/automaDICOM/node_modules/dwv/dist/dwv.min.js:4:10580)
    at g.dicom.DataWriter.writeDataElement (/Users/qashto/Dropbox/web/automaDICOM/node_modules/dwv/dist/dwv.min.js:4:11898)
    at g.dicom.DicomWriter.getBuffer (/Users/qashto/Dropbox/web/automaDICOM/node_modules/dwv/dist/dwv.min.js:4:14432)
    at edit (/Users/qashto/Dropbox/web/automaDICOM/src/automaDICOM.js:201:23)
    at setup (/Users/qashto/Dropbox/web/automaDICOM/src/automaDICOM.js:277:6)
    at module.exports (/Users/qashto/Dropbox/web/automaDICOM/src/automaDICOM.js:295:4)
```

**Comment by ivmartel** [comment]
Ok, this happens in the dicomWriter [flattenArrayOfTypedArrays](https://github.com/ivmartel/dwv/blob/master/src/dicom/dicomWriter.js#L540) function. It uses the TypedArray [set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/set) method which should be supported by most browsers.

In which browser/environment do you get this error?

**Comment by quinton-ashley** [comment]
I was using Node.js which uses Chrome.

**Comment by quinton-ashley** [comment]
I have Chrome 59.0.3071.115

**Comment by ivmartel** [comment]
Ok, looks recent enough!
This method is used for multi-frame data. It is possible that its input value (`initialArray`) is not correct. It could be interesting to log it to check it. Maybe the data you are trying to write is not supported...

**Comment by quinton-ashley** [comment]
I restarted my computer and it seems to run fine with the same set of data, weird.

**Comment by ivmartel** [comment]
Ok, closing for now. Feel free to reopen when the error comes back!
